// <auto-generated />
using System;
using System.Collections.Generic;
using McpGateway.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace McpGateway.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(McpGatewayDbContext))]
    [Migration("20260814160107_AddApprovalRequests")]
    partial class AddApprovalRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("McpGateway.Domain.Approvals.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("decided_by");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("decision_note");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequesterClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("requester_client_id");

                    b.Property<string>("Resource")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("resource");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("risk_level");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tool_name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("RequesterClientId", "ToolName", "Version", "Status");

                    b.ToTable("approval_requests", (string)null);
                });

            modelBuilder.Entity("McpGateway.Domain.Identities.GatewayIdentity", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("secret_hash");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("identity_type");

                    b.PrimitiveCollection<List<string>>("_grantedScopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("granted_scopes");

                    b.HasKey("ClientId");

                    b.ToTable("identities", (string)null);
                });

            modelBuilder.Entity("McpGateway.Domain.Tools.ToolDefinition", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.HasKey("Name");

                    b.ToTable("tools", (string)null);
                });

            modelBuilder.Entity("McpGateway.Domain.Tools.ToolDefinition", b =>
                {
                    b.OwnsMany("McpGateway.Domain.Tools.ToolVersion", "Versions", b1 =>
                        {
                            b1.Property<string>("ToolName")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("tool_name");

                            b1.Property<string>("Number")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("version");

                            b1.Property<bool>("ApprovalRequired")
                                .HasColumnType("boolean")
                                .HasColumnName("approval_required");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<string>("InputSchemaJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("input_schema");

                            b1.Property<string>("OutputSchemaJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("output_schema");

                            b1.Property<DateTimeOffset>("RegisteredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("registered_at");

                            b1.Property<string>("RiskLevel")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("risk_level");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.Property<int>("TimeoutSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("timeout_seconds");

                            b1.PrimitiveCollection<List<string>>("_requiredScopes")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("required_scopes");

                            b1.HasKey("ToolName", "Number");

                            b1.ToTable("tool_versions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ToolName");
                        });

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
